# Generated by Django 3.0.2 on 2020-02-02 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer', models.CharField(choices=[('CC', 'Colway Classic'), ('CI', 'Colway International'), ('NC', 'Non Colway')], max_length=2)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('price', models.PositiveIntegerField()),
                ('points', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('discontinued', models.BooleanField(default=False)),
                ('link', models.URLField(blank=True)),
                ('stock', models.PositiveIntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'db_table': 'product',
                'ordering': ('producer', 'name'),
            },
        ),
    ]
